integrations:
- integration_type: git_repo
  git_repo: ruichenmle/ava-llm-foundry
  git_branch: llama2-finetune # use your branch
  # git_commit: # OR use your commit hash
  pip_install: -e .[gpu]
  ssh_clone: false # Should be true if using a private repo



command: |
  cd ava-llm-foundry/scripts/
  python inference/convert_composer_to_hf_flan.py \
    --composer_path s3://mosaicml-68c98fa5-0b21-4c7b-b40b-c4482db8832a/avalaraGPT/model/flan-t5-large/q3-ipsprint-finetune/mono/ep10-ba70.pt \
    --hf_output_path s3://mosaicml-68c98fa5-0b21-4c7b-b40b-c4482db8832a/avalaraGPT/model/flan-t5-large/q3-ipsprint-finetune-hf/ \
    --output_precision bf16 \



image: mosaicml/pytorch:1.13.1_cu117-python3.10-ubuntu20.04
# Mosaic Cloud will use run_name (with a unique suffix) to populate the env var $COMPOSER_RUN_NAME

gpu_num: 8
gpu_type: a100_40gb
cluster: r8z3 # replace with your cluster here!


# Run Name
run_name: flan-t5-large-finetuned-model-conversion # If left blank, will be read from env var $RUN_NAME

